tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      git_remote: https://github.com/linuxbox2/
      force-branch: wip-lc-exphdr
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
